export const device = {
  connection: {
    isConnected: true,
    ipV4: '192.168.201.21',
    port: 4001,
    deviceAddress: 1,
  },
  address: {
    id: 1487740,
    city: 'деревня Раздоры',
    street: 'Липовой рощи',
    housingStockNumber: '1',
    corpus: 'цтп',
  },
  hubs: [
    {
      hub: {
        entryNumber: 2,
        hubNumber: 2,
        pipeNumber: 4,
        magistral: 'FeedFlow',
      },
      diameter: null,
      resource: 'ColdWaterSupply',
      housingMeteringDeviceType: 'FlowMeter',
      id: 1488447,
      transactionType: null,
      model: 'РС Питерфлоу 80-90А',
      serialNumber: '195368',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: '2018-09-10T03:00:00',
      futureCheckingDate: '2022-09-09T03:00:00',
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 2,
        hubNumber: 3,
        pipeNumber: 5,
        magistral: 'FeedFlow',
      },
      diameter: null,
      resource: 'ColdWaterSupply',
      housingMeteringDeviceType: 'FlowMeter',
      id: 1488448,
      transactionType: null,
      model: 'РС Питерфлоу 80-90А',
      serialNumber: '194776',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: '2018-09-10T03:00:00',
      futureCheckingDate: '2022-09-09T03:00:00',
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 2,
        hubNumber: 1,
        pipeNumber: 3,
        magistral: 'FeedFlow',
      },
      diameter: null,
      resource: 'ColdWaterSupply',
      housingMeteringDeviceType: 'FlowMeter',
      id: 1488449,
      transactionType: null,
      model: 'РС Питерфлоу 20-12А',
      serialNumber: '178766',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: '2018-09-10T03:00:00',
      futureCheckingDate: '2022-09-09T03:00:00',
      closingDate: null,
    },
  ],
  id: 1487756,
  transactionType: null,
  model: 'ТВ-7',
  serialNumber: '20101325',
  lastCommercialAccountingDate: null,
  futureCommercialAccountingDate: null,
  lastCheckingDate: null,
  futureCheckingDate: null,
  closingDate: null,
};
