export const device = {
  connection: {
    isConnected: true,
    ipV4: '192.168.201.14',
    port: 4001,
    deviceAddress: 1,
  },
  address: {
    id: 1487740,
    city: 'деревня Раздоры',
    street: 'Липовой рощи',
    housingStockNumber: '1',
    corpus: 'цтп',
  },
  hubs: [
    {
      hub: {
        entryNumber: 2,
        hubNumber: 4,
        pipeNumber: 3,
        magistral: 'FeedBackFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'FlowMeter',
      id: 1488440,
      transactionType: null,
      model: 'SONO 1500CT ДУ50',
      serialNumber: '126869',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 2,
        hubNumber: 4,
        pipeNumber: 3,
        magistral: 'FeedBackFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'TemperatureSensor',
      id: 1488459,
      transactionType: null,
      model: 'КТС-Б',
      serialNumber: '1817089',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 2,
        hubNumber: 4,
        pipeNumber: 2,
        magistral: 'FeedFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'FlowMeter',
      id: 1488437,
      transactionType: null,
      model: 'SONO 1500CT ДУ50',
      serialNumber: '126883',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 2,
        hubNumber: 4,
        pipeNumber: 2,
        magistral: 'FeedFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'TemperatureSensor',
      id: 1488438,
      transactionType: null,
      model: 'КТС-Б',
      serialNumber: '189554',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 1,
        hubNumber: 3,
        pipeNumber: 1,
        magistral: 'FeedBackFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'FlowMeter',
      id: 1488435,
      transactionType: null,
      model: 'SONO 1500CT ДУ80',
      serialNumber: '126812-1',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 1,
        hubNumber: 3,
        pipeNumber: 1,
        magistral: 'FeedBackFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'TemperatureSensor',
      id: 1488436,
      transactionType: null,
      model: 'КТС-Б',
      serialNumber: '188778',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 1,
        hubNumber: 3,
        pipeNumber: 0,
        magistral: 'FeedFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'FlowMeter',
      id: 1488433,
      transactionType: null,
      model: 'SONO 1500CT ДУ80',
      serialNumber: '116537-1',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
    {
      hub: {
        entryNumber: 1,
        hubNumber: 3,
        pipeNumber: 0,
        magistral: 'FeedFlow',
      },
      diameter: null,
      resource: 'Heat',
      housingMeteringDeviceType: 'TemperatureSensor',
      id: 1488434,
      transactionType: null,
      model: 'КТС-Б',
      serialNumber: '189554',
      managementFirm: {
        id: 1487736,
        name: 'ЖК "Спутник" (Самолёт-Сервис)',
        phoneNumber: null,
        information: null,
        timeZoneOffset: '03:00:00',
      },
      lastCommercialAccountingDate: null,
      futureCommercialAccountingDate: null,
      lastCheckingDate: null,
      futureCheckingDate: null,
      closingDate: null,
    },
  ],
  id: 1487754,
  transactionType: null,
  model: 'ТВ-7',
  serialNumber: '18061067',
  lastCommercialAccountingDate: null,
  futureCommercialAccountingDate: null,
  lastCheckingDate: null,
  futureCheckingDate: null,
  closingDate: null,
};
