import React from 'react';
import { rest } from 'msw';
import { setupServer } from 'msw/node';
import {
  render,
  fireEvent,
  waitFor,
  screen,
  waitForElementToBeRemoved,
} from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';
import DevicesFromSearch from '01/_pages/Devices';

const calculatorsResponse = {
  successResponse: {
    totalItems: 472,
    pageNumber: 1,
    pageSize: 5,
    items: [
      {
        connection: { ipV4: '', port: null, deviceAddress: null },
        isConnected: false,
        hasTasks: null,
        address: {
          id: 556,
          city: 'Нижнекамск',
          street: 'Баки Урманче',
          housingStockNumber: '28',
          corpus: null,
        },
        hubs: [
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 5,
              magistral: 'FeedFlow',
            },
            diameter: '50',
            resource: 'ColdWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2543038,
            transactionType: null,
            model: 'РС (72-А)',
            serialNumber: '044467',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2016-01-12T03:00:00',
            futureCommercialAccountingDate: '2019-08-07T03:00:00',
            lastCheckingDate: '2015-08-07T03:00:00',
            futureCheckingDate: '2019-08-07T03:00:00',
            closingDate: null,
          },
        ],
        nodes: [
          {
            id: 1603,
            number: 1,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'ColdWaterSupply',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2016-01-12T00:00:00',
            futureCommercialAccountingDate: '2019-08-07T00:00:00',
            calculatorId: 2538345,
            communicationPipes: [
              {
                id: 2539648,
                number: 5,
                entryNumber: 2,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 5,
                      magistral: 'FeedFlow',
                    },
                    diameter: '50',
                    resource: 'ColdWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2543038,
                    transactionType: null,
                    model: 'РС (72-А)',
                    serialNumber: '044467',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2016-01-12T03:00:00',
                    futureCommercialAccountingDate: '2019-08-07T03:00:00',
                    lastCheckingDate: '2015-08-07T03:00:00',
                    futureCheckingDate: '2019-08-07T03:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
        ],
        id: 2538345,
        transactionType: null,
        model: 'ТВ-7',
        serialNumber: '12000275',
        managementFirm: {
          id: 4,
          name: 'ООО УК"ПЖКХ-17"',
          phoneNumber: null,
          information: null,
          timeZoneOffset: '03:00:00',
        },
        lastCommercialAccountingDate: '2016-01-12T00:00:00',
        futureCommercialAccountingDate: '2019-08-07T00:00:00',
        lastCheckingDate: '2015-11-16T00:00:00',
        futureCheckingDate: '2019-11-16T00:00:00',
        closingDate: null,
      },
      {
        connection: { ipV4: null, port: null, deviceAddress: null },
        isConnected: true,
        hasTasks: null,
        address: {
          id: 245,
          city: 'Нижнекамск',
          street: 'Шинников',
          housingStockNumber: '44',
          corpus: null,
        },
        hubs: [
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 5,
              magistral: 'FeedFlow',
            },
            diameter: '50',
            resource: 'ColdWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2545921,
            transactionType: null,
            model: 'ПРЭМ',
            serialNumber: '263854',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-02-27T03:00:00',
            futureCommercialAccountingDate: '2019-10-20T03:00:00',
            lastCheckingDate: '2015-10-20T03:00:00',
            futureCheckingDate: '2019-10-20T03:00:00',
            closingDate: null,
          },
        ],
        nodes: [
          {
            id: 322,
            number: 1,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'ColdWaterSupply',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2019-02-27T00:00:00',
            futureCommercialAccountingDate: '2019-10-20T00:00:00',
            calculatorId: 2538948,
            communicationPipes: [
              {
                id: 2541656,
                number: 5,
                entryNumber: 2,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 5,
                      magistral: 'FeedFlow',
                    },
                    diameter: '50',
                    resource: 'ColdWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2545921,
                    transactionType: null,
                    model: 'ПРЭМ',
                    serialNumber: '263854',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-02-27T03:00:00',
                    futureCommercialAccountingDate: '2019-10-20T03:00:00',
                    lastCheckingDate: '2015-10-20T03:00:00',
                    futureCheckingDate: '2019-10-20T03:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
        ],
        id: 2538948,
        transactionType: null,
        model: 'ТВ-7.04.1',
        serialNumber: '14015563',
        managementFirm: {
          id: 4,
          name: 'ООО УК"ПЖКХ-17"',
          phoneNumber: null,
          information: null,
          timeZoneOffset: '03:00:00',
        },
        lastCommercialAccountingDate: '2019-02-27T03:00:00',
        futureCommercialAccountingDate: '2019-10-20T03:00:00',
        lastCheckingDate: '2015-12-12T03:00:00',
        futureCheckingDate: '2019-12-12T03:00:00',
        closingDate: null,
      },
      {
        connection: { ipV4: '192.168.105.26', port: 4001, deviceAddress: 1 },
        isConnected: true,
        hasTasks: null,
        address: {
          id: 229,
          city: 'Нижнекамск',
          street: 'Шинников',
          housingStockNumber: '1',
          corpus: null,
        },
        hubs: [
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 2,
              magistral: 'FeedFlow',
            },
            diameter: '65',
            resource: 'ColdWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2546391,
            transactionType: null,
            model: 'ПРЭМ',
            serialNumber: '384294',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2017-02-01T00:00:00',
            futureCommercialAccountingDate: '2020-09-02T00:00:00',
            lastCheckingDate: '2020-09-04T00:00:00',
            futureCheckingDate: '2024-09-04T00:00:00',
            closingDate: null,
          },
        ],
        nodes: [
          {
            id: 197,
            number: 1,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'ColdWaterSupply',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2017-01-31T21:00:00',
            futureCommercialAccountingDate: '2020-09-01T21:00:00',
            calculatorId: 2539007,
            communicationPipes: [
              {
                id: 3233252,
                number: 2,
                entryNumber: 1,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 2,
                      magistral: 'FeedFlow',
                    },
                    diameter: '65',
                    resource: 'ColdWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2546391,
                    transactionType: null,
                    model: 'ПРЭМ',
                    serialNumber: '384294',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2017-02-01T00:00:00',
                    futureCommercialAccountingDate: '2020-09-02T00:00:00',
                    lastCheckingDate: '2020-09-04T00:00:00',
                    futureCheckingDate: '2024-09-04T00:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
        ],
        id: 2539007,
        transactionType: null,
        model: 'ВКТ-7',
        serialNumber: '160238',
        managementFirm: {
          id: 4,
          name: 'ООО УК"ПЖКХ-17"',
          phoneNumber: null,
          information: null,
          timeZoneOffset: '03:00:00',
        },
        lastCommercialAccountingDate: '2017-02-01T03:00:00',
        futureCommercialAccountingDate: '2020-09-02T03:00:00',
        lastCheckingDate: '2016-12-14T03:00:00',
        futureCheckingDate: '2020-12-14T03:00:00',
        closingDate: null,
      },
      {
        connection: { ipV4: '', port: null, deviceAddress: null },
        isConnected: false,
        hasTasks: null,
        address: {
          id: 246,
          city: 'Нижнекамск',
          street: 'Шинников',
          housingStockNumber: '46',
          corpus: null,
        },
        hubs: [
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 0,
              magistral: 'FeedFlow',
            },
            diameter: null,
            resource: 'Heat',
            housingMeteringDeviceType: 'TemperatureSensor',
            id: 2543058,
            transactionType: null,
            model: 'КТСБ',
            serialNumber: '145201',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-10-18T03:00:00',
            futureCommercialAccountingDate: '2020-12-20T03:00:00',
            lastCheckingDate: '2018-04-14T03:00:00',
            futureCheckingDate: '2022-04-14T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 0,
              magistral: 'FeedFlow',
            },
            diameter: '50',
            resource: 'Heat',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2543059,
            transactionType: null,
            model: 'РСМ 05.05',
            serialNumber: '282263',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-10-18T03:00:00',
            futureCommercialAccountingDate: '2020-12-20T03:00:00',
            lastCheckingDate: '2019-08-16T03:00:00',
            futureCheckingDate: '2023-08-16T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 3,
              magistral: 'FeedBackFlow',
            },
            diameter: '32',
            resource: 'HotWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2543054,
            transactionType: null,
            model: 'РСМ 05.05',
            serialNumber: '285387',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2020-08-12T00:00:00',
            futureCommercialAccountingDate: '2020-12-20T00:00:00',
            lastCheckingDate: '2018-04-23T00:00:00',
            futureCheckingDate: '2022-04-23T00:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 2,
              magistral: 'FeedFlow',
            },
            diameter: '50',
            resource: 'HotWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2543055,
            transactionType: null,
            model: 'РСМ 05.05',
            serialNumber: '286643',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2020-08-12T00:00:00',
            futureCommercialAccountingDate: '2020-12-20T00:00:00',
            lastCheckingDate: '2020-01-13T00:00:00',
            futureCheckingDate: '2024-01-13T00:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 2,
              magistral: 'FeedFlow',
            },
            diameter: null,
            resource: 'HotWaterSupply',
            housingMeteringDeviceType: 'TemperatureSensor',
            id: 2543061,
            transactionType: null,
            model: 'КТСБ',
            serialNumber: '157725',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2020-08-11T21:00:00',
            futureCommercialAccountingDate: '2020-12-19T21:00:00',
            lastCheckingDate: '2020-05-25T18:00:00',
            futureCheckingDate: '2024-05-25T18:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 1,
              magistral: 'FeedBackFlow',
            },
            diameter: null,
            resource: 'Heat',
            housingMeteringDeviceType: 'TemperatureSensor',
            id: 2543056,
            transactionType: null,
            model: 'КТСБ',
            serialNumber: '145183',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-10-18T03:00:00',
            futureCommercialAccountingDate: '2020-12-20T03:00:00',
            lastCheckingDate: '2018-04-14T03:00:00',
            futureCheckingDate: '2022-04-14T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 1,
              magistral: 'FeedBackFlow',
            },
            diameter: '50',
            resource: 'Heat',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2543057,
            transactionType: null,
            model: 'РСМ 05.05',
            serialNumber: '285458',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-10-18T03:00:00',
            futureCommercialAccountingDate: '2020-12-20T03:00:00',
            lastCheckingDate: '2018-05-24T03:00:00',
            futureCheckingDate: '2022-05-24T03:00:00',
            closingDate: null,
          },
        ],
        nodes: [
          {
            id: 1624,
            number: 1,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'HotWaterSupply',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2020-08-11T21:00:00',
            futureCommercialAccountingDate: '2020-12-19T21:00:00',
            calculatorId: 2538334,
            communicationPipes: [
              {
                id: 2539660,
                number: 3,
                entryNumber: 2,
                hubNumber: null,
                magistral: 'FeedBackFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 3,
                      magistral: 'FeedBackFlow',
                    },
                    diameter: '32',
                    resource: 'HotWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2543054,
                    transactionType: null,
                    model: 'РСМ 05.05',
                    serialNumber: '285387',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2020-08-12T00:00:00',
                    futureCommercialAccountingDate: '2020-12-20T00:00:00',
                    lastCheckingDate: '2018-04-23T00:00:00',
                    futureCheckingDate: '2022-04-23T00:00:00',
                    closingDate: null,
                  },
                ],
              },
              {
                id: 3233034,
                number: 2,
                entryNumber: 2,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 2,
                      magistral: 'FeedFlow',
                    },
                    diameter: '50',
                    resource: 'HotWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2543055,
                    transactionType: null,
                    model: 'РСМ 05.05',
                    serialNumber: '286643',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2020-08-12T00:00:00',
                    futureCommercialAccountingDate: '2020-12-20T00:00:00',
                    lastCheckingDate: '2020-01-13T00:00:00',
                    futureCheckingDate: '2024-01-13T00:00:00',
                    closingDate: null,
                  },
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 2,
                      magistral: 'FeedFlow',
                    },
                    diameter: null,
                    resource: 'HotWaterSupply',
                    housingMeteringDeviceType: 'TemperatureSensor',
                    id: 2543061,
                    transactionType: null,
                    model: 'КТСБ',
                    serialNumber: '157725',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2020-08-11T21:00:00',
                    futureCommercialAccountingDate: '2020-12-19T21:00:00',
                    lastCheckingDate: '2020-05-25T18:00:00',
                    futureCheckingDate: '2024-05-25T18:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
          {
            id: 1625,
            number: 2,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'Heat',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2019-10-18T00:00:00',
            futureCommercialAccountingDate: '2020-12-20T00:00:00',
            calculatorId: 2538334,
            communicationPipes: [
              {
                id: 2539658,
                number: 0,
                entryNumber: 1,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 0,
                      magistral: 'FeedFlow',
                    },
                    diameter: null,
                    resource: 'Heat',
                    housingMeteringDeviceType: 'TemperatureSensor',
                    id: 2543058,
                    transactionType: null,
                    model: 'КТСБ',
                    serialNumber: '145201',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-10-18T03:00:00',
                    futureCommercialAccountingDate: '2020-12-20T03:00:00',
                    lastCheckingDate: '2018-04-14T03:00:00',
                    futureCheckingDate: '2022-04-14T03:00:00',
                    closingDate: null,
                  },
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 0,
                      magistral: 'FeedFlow',
                    },
                    diameter: '50',
                    resource: 'Heat',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2543059,
                    transactionType: null,
                    model: 'РСМ 05.05',
                    serialNumber: '282263',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-10-18T03:00:00',
                    futureCommercialAccountingDate: '2020-12-20T03:00:00',
                    lastCheckingDate: '2019-08-16T03:00:00',
                    futureCheckingDate: '2023-08-16T03:00:00',
                    closingDate: null,
                  },
                ],
              },
              {
                id: 2539659,
                number: 1,
                entryNumber: 1,
                hubNumber: null,
                magistral: 'FeedBackFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 1,
                      magistral: 'FeedBackFlow',
                    },
                    diameter: null,
                    resource: 'Heat',
                    housingMeteringDeviceType: 'TemperatureSensor',
                    id: 2543056,
                    transactionType: null,
                    model: 'КТСБ',
                    serialNumber: '145183',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-10-18T03:00:00',
                    futureCommercialAccountingDate: '2020-12-20T03:00:00',
                    lastCheckingDate: '2018-04-14T03:00:00',
                    futureCheckingDate: '2022-04-14T03:00:00',
                    closingDate: null,
                  },
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 1,
                      magistral: 'FeedBackFlow',
                    },
                    diameter: '50',
                    resource: 'Heat',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2543057,
                    transactionType: null,
                    model: 'РСМ 05.05',
                    serialNumber: '285458',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-10-18T03:00:00',
                    futureCommercialAccountingDate: '2020-12-20T03:00:00',
                    lastCheckingDate: '2018-05-24T03:00:00',
                    futureCheckingDate: '2022-05-24T03:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
        ],
        id: 2538334,
        transactionType: null,
        model: 'ТЭМ-106',
        serialNumber: '165089',
        managementFirm: {
          id: 4,
          name: 'ООО УК"ПЖКХ-17"',
          phoneNumber: null,
          information: null,
          timeZoneOffset: '03:00:00',
        },
        lastCommercialAccountingDate: '2019-10-17T21:00:00',
        futureCommercialAccountingDate: '2020-12-19T21:00:00',
        lastCheckingDate: '2016-12-19T21:00:00',
        futureCheckingDate: '2020-12-19T21:00:00',
        closingDate: null,
      },
      {
        connection: { ipV4: '192.168.100.26', port: 4001, deviceAddress: 0 },
        isConnected: false,
        hasTasks: null,
        address: {
          id: 236,
          city: 'Нижнекамск',
          street: 'Шинников',
          housingStockNumber: '21',
          corpus: null,
        },
        hubs: [
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 0,
              magistral: 'FeedFlow',
            },
            diameter: null,
            resource: 'Heat',
            housingMeteringDeviceType: 'TemperatureSensor',
            id: 2544026,
            transactionType: null,
            model: 'КТСБ',
            serialNumber: '1343309',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-10-09T03:00:00',
            futureCommercialAccountingDate: '2020-12-22T03:00:00',
            lastCheckingDate: '2019-06-19T03:00:00',
            futureCheckingDate: '2023-06-19T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 0,
              magistral: 'FeedFlow',
            },
            diameter: '40',
            resource: 'Heat',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2544027,
            transactionType: null,
            model: 'ПРЭМ',
            serialNumber: '372782',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-10-09T03:00:00',
            futureCommercialAccountingDate: '2020-12-22T03:00:00',
            lastCheckingDate: '2019-06-13T03:00:00',
            futureCheckingDate: '2023-06-13T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 5,
              magistral: 'FeedFlow',
            },
            diameter: '40',
            resource: 'ColdWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2544021,
            transactionType: null,
            model: 'ПРЭМ',
            serialNumber: '386661',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2016-05-10T03:00:00',
            futureCommercialAccountingDate: '2019-08-12T03:00:00',
            lastCheckingDate: '2019-07-30T03:00:00',
            futureCheckingDate: '2023-07-30T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 3,
              magistral: 'FeedFlow',
            },
            diameter: null,
            resource: 'HotWaterSupply',
            housingMeteringDeviceType: 'TemperatureSensor',
            id: 2544023,
            transactionType: null,
            model: 'КТПТР',
            serialNumber: '9420',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-08-19T03:00:00',
            futureCommercialAccountingDate: '2020-12-22T03:00:00',
            lastCheckingDate: '2019-06-19T03:00:00',
            futureCheckingDate: '2023-06-19T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 3,
              magistral: 'FeedFlow',
            },
            diameter: '40',
            resource: 'HotWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2544025,
            transactionType: null,
            model: 'ПРЭМ',
            serialNumber: '327919',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-08-19T03:00:00',
            futureCommercialAccountingDate: '2020-12-22T03:00:00',
            lastCheckingDate: '2019-03-27T03:00:00',
            futureCheckingDate: '2023-03-27T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 2,
              hubNumber: null,
              pipeNumber: 4,
              magistral: 'FeedBackFlow',
            },
            diameter: '32',
            resource: 'HotWaterSupply',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2544022,
            transactionType: null,
            model: 'ПРЭМ',
            serialNumber: '251946',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-08-19T03:00:00',
            futureCommercialAccountingDate: '2020-12-22T03:00:00',
            lastCheckingDate: '2019-04-05T03:00:00',
            futureCheckingDate: '2023-04-05T03:00:00',
            closingDate: null,
          },
          {
            hub: {
              entryNumber: 1,
              hubNumber: null,
              pipeNumber: 1,
              magistral: 'FeedBackFlow',
            },
            diameter: '40',
            resource: 'Heat',
            housingMeteringDeviceType: 'FlowMeter',
            id: 2544032,
            transactionType: null,
            model: 'ПРЭМ',
            serialNumber: '356830',
            managementFirm: {
              id: 4,
              name: 'ООО УК"ПЖКХ-17"',
              phoneNumber: null,
              information: null,
              timeZoneOffset: '03:00:00',
            },
            lastCommercialAccountingDate: '2019-10-09T03:00:00',
            futureCommercialAccountingDate: '2020-12-22T03:00:00',
            lastCheckingDate: '2019-04-04T03:00:00',
            futureCheckingDate: '2023-04-04T03:00:00',
            closingDate: null,
          },
        ],
        nodes: [
          {
            id: 1186,
            number: 1,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'ColdWaterSupply',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2016-05-10T00:00:00',
            futureCommercialAccountingDate: '2019-08-12T00:00:00',
            calculatorId: 2538549,
            communicationPipes: [
              {
                id: 2540465,
                number: 5,
                entryNumber: 2,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 5,
                      magistral: 'FeedFlow',
                    },
                    diameter: '40',
                    resource: 'ColdWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2544021,
                    transactionType: null,
                    model: 'ПРЭМ',
                    serialNumber: '386661',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2016-05-10T03:00:00',
                    futureCommercialAccountingDate: '2019-08-12T03:00:00',
                    lastCheckingDate: '2019-07-30T03:00:00',
                    futureCheckingDate: '2023-07-30T03:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
          {
            id: 1187,
            number: 2,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'HotWaterSupply',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2019-08-19T00:00:00',
            futureCommercialAccountingDate: '2020-12-22T00:00:00',
            calculatorId: 2538549,
            communicationPipes: [
              {
                id: 2540338,
                number: 3,
                entryNumber: 2,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 3,
                      magistral: 'FeedFlow',
                    },
                    diameter: null,
                    resource: 'HotWaterSupply',
                    housingMeteringDeviceType: 'TemperatureSensor',
                    id: 2544023,
                    transactionType: null,
                    model: 'КТПТР',
                    serialNumber: '9420',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-08-19T03:00:00',
                    futureCommercialAccountingDate: '2020-12-22T03:00:00',
                    lastCheckingDate: '2019-06-19T03:00:00',
                    futureCheckingDate: '2023-06-19T03:00:00',
                    closingDate: null,
                  },
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 3,
                      magistral: 'FeedFlow',
                    },
                    diameter: '40',
                    resource: 'HotWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2544025,
                    transactionType: null,
                    model: 'ПРЭМ',
                    serialNumber: '327919',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-08-19T03:00:00',
                    futureCommercialAccountingDate: '2020-12-22T03:00:00',
                    lastCheckingDate: '2019-03-27T03:00:00',
                    futureCheckingDate: '2023-03-27T03:00:00',
                    closingDate: null,
                  },
                ],
              },
              {
                id: 2540439,
                number: 4,
                entryNumber: 2,
                hubNumber: null,
                magistral: 'FeedBackFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 2,
                      hubNumber: null,
                      pipeNumber: 4,
                      magistral: 'FeedBackFlow',
                    },
                    diameter: '32',
                    resource: 'HotWaterSupply',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2544022,
                    transactionType: null,
                    model: 'ПРЭМ',
                    serialNumber: '251946',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-08-19T03:00:00',
                    futureCommercialAccountingDate: '2020-12-22T03:00:00',
                    lastCheckingDate: '2019-04-05T03:00:00',
                    futureCheckingDate: '2023-04-05T03:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
          {
            id: 1188,
            number: 3,
            nodeStatus: 'Сдан на коммерческий учет',
            resource: 'Heat',
            serviceZone: 'Апартаменты',
            lastCommercialAccountingDate: '2019-10-09T00:00:00',
            futureCommercialAccountingDate: '2020-12-22T00:00:00',
            calculatorId: 2538549,
            communicationPipes: [
              {
                id: 2540336,
                number: 0,
                entryNumber: 1,
                hubNumber: null,
                magistral: 'FeedFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 0,
                      magistral: 'FeedFlow',
                    },
                    diameter: null,
                    resource: 'Heat',
                    housingMeteringDeviceType: 'TemperatureSensor',
                    id: 2544026,
                    transactionType: null,
                    model: 'КТСБ',
                    serialNumber: '1343309',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-10-09T03:00:00',
                    futureCommercialAccountingDate: '2020-12-22T03:00:00',
                    lastCheckingDate: '2019-06-19T03:00:00',
                    futureCheckingDate: '2023-06-19T03:00:00',
                    closingDate: null,
                  },
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 0,
                      magistral: 'FeedFlow',
                    },
                    diameter: '40',
                    resource: 'Heat',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2544027,
                    transactionType: null,
                    model: 'ПРЭМ',
                    serialNumber: '372782',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-10-09T03:00:00',
                    futureCommercialAccountingDate: '2020-12-22T03:00:00',
                    lastCheckingDate: '2019-06-13T03:00:00',
                    futureCheckingDate: '2023-06-13T03:00:00',
                    closingDate: null,
                  },
                ],
              },
              {
                id: 2540337,
                number: 1,
                entryNumber: 1,
                hubNumber: null,
                magistral: 'FeedBackFlow',
                devices: [
                  {
                    hub: {
                      entryNumber: 1,
                      hubNumber: null,
                      pipeNumber: 1,
                      magistral: 'FeedBackFlow',
                    },
                    diameter: '40',
                    resource: 'Heat',
                    housingMeteringDeviceType: 'FlowMeter',
                    id: 2544032,
                    transactionType: null,
                    model: 'ПРЭМ',
                    serialNumber: '356830',
                    managementFirm: {
                      id: 4,
                      name: 'ООО УК"ПЖКХ-17"',
                      phoneNumber: null,
                      information: null,
                      timeZoneOffset: '03:00:00',
                    },
                    lastCommercialAccountingDate: '2019-10-09T03:00:00',
                    futureCommercialAccountingDate: '2020-12-22T03:00:00',
                    lastCheckingDate: '2019-04-04T03:00:00',
                    futureCheckingDate: '2023-04-04T03:00:00',
                    closingDate: null,
                  },
                ],
              },
            ],
          },
        ],
        id: 2538549,
        transactionType: null,
        model: 'ТВ-7',
        serialNumber: '13003520',
        managementFirm: {
          id: 4,
          name: 'ООО УК"ПЖКХ-17"',
          phoneNumber: null,
          information: null,
          timeZoneOffset: '03:00:00',
        },
        lastCommercialAccountingDate: '2019-10-08T12:00:00',
        futureCommercialAccountingDate: '2020-12-21T12:00:00',
        lastCheckingDate: '2019-10-08T12:00:00',
        futureCheckingDate: '2020-12-21T12:00:00',
        closingDate: null,
      },
    ],
    totalPages: 95,
    hasPreviousPage: false,
    hasNextPage: true,
    nextPageNumber: 2,
    previousPageNumber: 1,
  },
};

const server = setupServer(
  rest.get('Calculators/?pageNumber=1&pageSize=5', (req, res, ctx) => {
    return res(ctx.json({ ...calculatorsResponse.successResponse }));
  })
);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

test('loads and displays greeting', async () => {
  render(<DevicesFromSearch />);

  // fireEvent.click(screen.getByText('Load Greeting'));
  screen.debug();
  await waitForElementToBeRemoved(() => screen.getByLabelText(/загрузка/i));
  // await waitFor(() => screen.getByRole('heading'));

  // expect(screen.getByRole('heading')).toHaveTextContent('hello there');
  // expect(screen.getByRole('button')).toHaveAttribute('disabled');
});

// test('handles server error', async () => {
//   server.use(
//     rest.get('/greeting', (req, res, ctx) => {
//       return res(ctx.status(500));
//     })
//   );
//
//   fireEvent.click(screen.getByText('Load Greeting'));
//
//   await waitFor(() => screen.getByRole('alert'));
//
//   expect(screen.getByRole('alert')).toHaveTextContent('Oops, failed to fetch!');
//   expect(screen.getByRole('button')).not.toHaveAttribute('disabled');
// });
