export const mockData = [
  {
    managingFirm: 'ООО УК "Жилье"',
    houseManagement: 'ЖКХ 9',
    coldWaterSupplyPlan: 79,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 83,
    hotWaterSupplyValue: 0,
    electricityPlan: 96,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'Жилтехсервис',
    coldWaterSupplyPlan: 10281,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 10263,
    hotWaterSupplyValue: 0,
    electricityPlan: 6919,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'ЖКХ 10',
    coldWaterSupplyPlan: 8627,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 8651,
    hotWaterSupplyValue: 0,
    electricityPlan: 5819,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'ЖКХ 11',
    coldWaterSupplyPlan: 6792,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 6762,
    hotWaterSupplyValue: 0,
    electricityPlan: 4485,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'ЖКХ 8',
    coldWaterSupplyPlan: 7417,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 7400,
    hotWaterSupplyValue: 0,
    electricityPlan: 5411,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'ЖКХ 9',
    coldWaterSupplyPlan: 6354,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 6358,
    hotWaterSupplyValue: 0,
    electricityPlan: 4873,
    electricityValue: 0,
    heatPlan: 133,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'ЖКХ-17',
    coldWaterSupplyPlan: 8245,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 8292,
    hotWaterSupplyValue: 0,
    electricityPlan: 6415,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'Кама',
    coldWaterSupplyPlan: 9379,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 9361,
    hotWaterSupplyValue: 0,
    electricityPlan: 6415,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'ООО УК ЖКХ +',
    coldWaterSupplyPlan: 6326,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 6320,
    hotWaterSupplyValue: 0,
    electricityPlan: 4030,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'ООО УК КРАСНЫЙ КЛЮЧ',
    coldWaterSupplyPlan: 0,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 0,
    hotWaterSupplyValue: 0,
    electricityPlan: 989,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
  {
    managingFirm: 'ООО УК"ПЖКХ-17"',
    houseManagement: 'Центр',
    coldWaterSupplyPlan: 7514,
    coldWaterSupplyValue: 0,
    hotWaterSupplyPlan: 7499,
    hotWaterSupplyValue: 0,
    electricityPlan: 5860,
    electricityValue: 0,
    heatPlan: 0,
    heatValue: 0,
  },
];
