export const disabledValuesByType = {
  empty: ['serialNumber',
    'lastCheckingDate',
    'futureCheckingDate',
    'lastCommercialAccountingDate',
    'futureCommercialAccountingDate',
    'housingMeteringDeviceType',
    'resource',
    'model',
    'isConnected',
    'entryNumber',
    'hubNumber',
    'pipeNumber',
    'calculatorId'],
  edit: ['serialNumber',
    'resource',
    'isConnected',
    'entryNumber',
    'hubNumber',
    'pipeNumber',
    'calculatorId'],
  add: [
    'housingMeteringDeviceType',
    'resource',
    'isConnected',
    'entryNumber',
    'hubNumber',
    'pipeNumber',
    'calculatorId'],
};

export const selectedTemplate = {
  serialNumber: '',
  model: '',
  lastCommercialAccountingDate: null,
  futureCommercialAccountingDate: null,
  lastCheckingDate: null,
  futureCheckingDate: null,
};
